@host = http://127.0.0.1:8000

### Register User
POST {{host}}/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@example.com",
    "password": "password123",
    "password_confirmation": "password123"
}


### Login User
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
     "username": "test@example.com",
    "password": "password123"
}