@host = http://127.0.0.1:8000

### Register User
POST {{host}}/api/register
Accept: application/json
Content-Type: application/json

{"first_name":"Saroj","last_name":"Guragain","middle_name":"","email":"guragainsaroj40@gmail.com","password":"password","password_confirmation":"password","role":"Admin","status":"Active"}
### {
#     "name": "Test User",
#     "email": "test@example.com",
#     "password": "password123",
#     "password_confirmation": "password123"
# }


### Login User
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
    //"username": "guragainsaroj40@gmail.com",
     "email": "admin@jhyomo.com",
     "password": "password",
     "remember":true
}

### Logout User
POST {{host}}/api/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 8|5PZkSA0UzhUBudpC63jVttuXhaUvsXPMVDjDjwyv44743be0

#### Get Authenticated User
GET {{host}}/api/users
Accept: application/json
Authorization: Bearer 30|7MzMdNyFb64pGxof0i1E8AKkxKKw6omXzlEXgMcVbc23b475
